import json, argparse
from collections import defaultdict
from datetime import datetime, timezone

def load_runs(path):
    with open(path) as f:
        return json.load(f)

def aggregate(runs):
    chars = defaultdict(lambda: {"runs": []})

    for run in runs:
        for member in run["roster"]:
            key = f'{member["region"]}-{member["name"]}-{member["realm"]}'
            chars[key]["runs"].append({
                "level": run["mythic_level"],
                "dungeon": run["dungeon"],
                "status": run["status"],
                "completed_at": run["completed_at"],
                "score": run["score"],
                "class": member["class"],
                "spec": member["spec"],
                "role": member["role"],
            })

    summary = {}
    for key, data in chars.items():
        runs_list = data["runs"]
        runs_list.sort(key=lambda r: r["completed_at"], reverse=True)
        latest = runs_list[0]

        levels = [r["level"] for r in runs_list]
        timed = sum(1 for r in runs_list if r["status"] == "finished")
        depleted = len(runs_list) - timed
        dungeons_covered = len(set(r["dungeon"] for r in runs_list))

        summary[key] = {
            "class": latest["class"],
            "spec": latest["spec"],
            "role": latest["role"],
            "highest_level": max(levels),
            "run_count": len(runs_list),
            "timed_count": timed,
            "depleted_count": depleted,
            "dungeons_covered": dungeons_covered,
            "last_seen": latest["completed_at"],
            "best_score": max(r["score"] for r in runs_list),
        }

    return summary

def lua_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def to_lua(summary, out_path, season, generated_at, failed_dungeons):
    lines = []
    lines.append("-- Keyvet data file")
    lines.append("-- AUTO-GENERATED by build_lua.py — do not edit by hand")
    lines.append("--")
    lines.append("-- SCOPE NOTE: This data reflects the TOP-RANKED 6+ Mythic+ runs per")
    lines.append("-- dungeon this season, as returned by Raider.IO's /mythic-plus/runs")
    lines.append("-- endpoint (capped at 1000 pages / 20,020 runs per dungeon). It is")
    lines.append("-- NOT a complete record of every 6+ run this season. A character")
    lines.append("-- missing from this data may simply not rank highly enough to appear")
    lines.append("-- here — absence is not a negative signal.")
    lines.append("--")
    lines.append(f'-- Season: {season}')
    lines.append(f'-- Generated: {generated_at}')
    lines.append(f'-- Characters: {len(summary)}')
    if failed_dungeons:
        lines.append(f'-- WARNING: partial data — these dungeons failed to fetch this run: {", ".join(failed_dungeons)}')
    lines.append("")
    lines.append("KeyvetDB = {")

    for key, c in summary.items():
        lines.append(f'  ["{lua_escape(key)}"] = {{')
        lines.append(f'    class = "{lua_escape(c["class"])}",')
        lines.append(f'    spec = "{lua_escape(c["spec"])}",')
        lines.append(f'    role = "{lua_escape(c["role"])}",')
        lines.append(f'    highestLevel = {c["highest_level"]},')
        lines.append(f'    runCount = {c["run_count"]},')
        lines.append(f'    timedCount = {c["timed_count"]},')
        lines.append(f'    depletedCount = {c["depleted_count"]},')
        lines.append(f'    dungeonsCovered = {c["dungeons_covered"]},')
        lines.append(f'    lastSeen = "{lua_escape(c["last_seen"])}",')
        lines.append(f'    bestScore = {c["best_score"]},')
        lines.append("  },")

    lines.append("}")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--in", dest="in_path", required=True)
    parser.add_argument("--out", dest="out_path", required=True)
    args = parser.parse_args()

    wrapper = load_runs(args.in_path)
    runs = wrapper["runs"]
    season = wrapper["season"]
    failed_dungeons = wrapper.get("failed_dungeons", [])

    print(f"Loaded {len(runs)} run records (season {season})")
    if failed_dungeons:
        print(f"Note: partial data, failed dungeons: {failed_dungeons}")

    summary = aggregate(runs)
    print(f"Aggregated to {len(summary)} unique characters")

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    to_lua(summary, args.out_path, season, generated_at, failed_dungeons)
    print(f"Wrote {args.out_path}")